### ISSUE TITLE
Unable to load gopher.obj

### ISSUE THREAD

**Issue by kylewolfe** [luxengine/lux#3]
Forgive me if this is too much to take on. I'm not familiar with any 3d development and just wanted to play around. I wanted to load up a demo with the gopher object. Please see https://github.com/kylewolfe/lux/tree/examples/examples/gopher

```
go run gopher.go 
panic: Can't read file

goroutine 1 [running]:
github.com/luxengine/lux/utils.LoadObject(0x5fe090, 0x12, 0xc820016200, 0x0)
	/home/kyle/projects/go/src/github.com/luxengine/lux/utils/objloader.go:69 +0xa05
luxengine.net/lux.NewWavefrontModelFromFile(0x5fe090, 0x12, 0x0, 0x0)
	/home/kyle/projects/go/src/luxengine.net/lux/models.go:28 +0x57
main.main()
	/home/kyle/projects/go/src/luxengine.net/lux/examples/gopher/gopher.go:7 +0x31

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1
exit status 2
```

**Comment by hydroflame** [comment]
No don't worry I'm very excited for someone to use my software. The problem is that your model contains only vertex position data. The loader expected normal and texture coordinate too.

**Comment by kylewolfe** [comment]
So I googled and found that entering edit mode and making the project a "smart uv project" would add texture coordinates. I re-exported the obj file with everything selected except for "selection only" and "animation". Am I still missing a type of coordinate?

**Comment by hydroflame** [comment]
so select your object, go to edit mode, press  `a` to select all vertices (or `aa`), press `u` select `unwrap` (or `smart uv unwrap`) you can click the box in the bottom left and select `uv/image editor` instead of `3D view` to see if you unwrapped. you should see a some orange (you need to still have all the vertices selected). then go back to 3d view, press `w` then `shade smooth` or `shade flat` depending on your model (for the gopher: `shade smooth`) then click `File`>`export`>`wavefront (.obj)`
have selected: `include edges`, `write normals`, `include UVs`, `Triangulate faces`, `Objects as OBJ objects`. The resulting fiel SHOULD load. My loader is kinda primitive. 

If none of this works, you can use models here https://github.com/hydroflame/lux_dev_env/tree/master/assets/models
